version: '2.1'
orbs:
  node: circleci/node@5.0.2
jobs:
  check-formatting:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: cd server/; yarn
      - run: cd server/; yarn prettier --check ../
workflows:
  test_my_app:
    jobs:
      - check-formatting
